repos:
  - repo: local
    hooks:
      - id: backend-lint
        name: backend lint
        entry: make backend-lint
        language: system
        pass_filenames: false
      - id: backend-tests
        name: backend tests
        entry: make backend-tests
        language: system
        pass_filenames: false
      - id: frontend-lint
        name: frontend lint
        entry: make frontend-lint
        language: system
        pass_filenames: false
      - id: frontend-typecheck
        name: frontend typecheck
        entry: make frontend-typecheck
        language: system
        pass_filenames: false
      - id: markdown-lint
        name: markdown lint
        entry: make markdown-lint
        language: system
        pass_filenames: false
